[project]
name = "patient-framework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "aidancheema", email = "aidancheema@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "mypy>=2.3.0",
    "requests>=2.34.2",
]

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-mock>=3.15.1",
]

[tool.pytest.ini_options]
pythonpath=["src"]
